include_guard(GLOBAL)
get_filename_component(_GPLATFORM_SDK_ROOT "${CMAKE_CURRENT_LIST_DIR}/../../.." ABSOLUTE)
include(CMakeFindDependencyMacro)
find_dependency(Qt6 6.9.3 EXACT COMPONENTS Core Gui Qml Quick QuickControls2 Network Quick3D Concurrent Multimedia Widgets OpenGL OpenGLWidgets Sql)
find_dependency(Threads)
find_dependency(OpenGL)
include("${CMAKE_CURRENT_LIST_DIR}/GPlatformSDKDependencies.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/GPlatformSDKTargets.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/ModuleRegistration.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/RendererModuleBoundaries.cmake")
add_library(Foundation::Foundation ALIAS Foundation)
add_library(Foundation::QmlRegistration ALIAS GPlatformQmlRegistration)
add_library(GPlatform::Tr ALIAS Tr)
add_library(KDAB::kddockwidgets ALIAS kddockwidgets)
add_library(GPlatform::RendererBackendSDK ALIAS GPlatformRendererBackendSDK)
add_library(cereal::cereal ALIAS cereal)
set(spdlog_DIR "${CMAKE_CURRENT_LIST_DIR}")
set(Eigen3_DIR "${CMAKE_CURRENT_LIST_DIR}")
set(GPLATFORM_ENABLE_LIBSLICER "ON")
set(GPLATFORM_ENABLE_FILAMENT "ON")
set(SMOOTHUI_BUILD_STATIC_LIB "ON")
set(ENABLE_BREAKPAD "ON")
set(BREAKPAD_FOUND "TRUE")
set(VTK_FOUND "1")
set(embree_FOUND "1")
set(HOTLOAD_ENABLED OFF CACHE BOOL "Enable application QML hot reload")
set(BREAKPAD_INCLUDE_DIRS "${_GPLATFORM_SDK_ROOT}/include/dependencies/breakpad-v2023.06.01/src/src;${_GPLATFORM_SDK_ROOT}/include/dependencies/breakpad-v2023.06.01/include;${_GPLATFORM_SDK_ROOT}/include/dependencies/breakpad-v2023.06.01/src/src;${_GPLATFORM_SDK_ROOT}/include/dependencies/breakpad-v2023.06.01/include;${_GPLATFORM_SDK_ROOT}/include/dependencies/breakpad-v2023.06.01/include/client/mac;${_GPLATFORM_SDK_ROOT}/include/dependencies/breakpad-v2023.06.01/include/common/mac")
set(TR_PO2MO_SCRIPT "${_GPLATFORM_SDK_ROOT}/tools/po2mo.py")
set(TR_EXTRACT_SCRIPT "${_GPLATFORM_SDK_ROOT}/tools/tr_extract.py")
set(LIBSLICER_RESOURCE_DIR "${_GPLATFORM_SDK_ROOT}/share/libslicer")
set(GPLATFORM_LIBSLICER_INSTALL_DIR "${_GPLATFORM_SDK_ROOT}")
function(gplatform_add_renderer_resources target)
  set_source_files_properties("${_GPLATFORM_SDK_ROOT}/share/renderer/monkey.obj" PROPERTIES QT_RESOURCE_ALIAS "monkey.obj")
  set_source_files_properties("${_GPLATFORM_SDK_ROOT}/share/renderer/pillars_2k.hdr" PROPERTIES QT_RESOURCE_ALIAS "pillars_2k.hdr")
  set_source_files_properties("${_GPLATFORM_SDK_ROOT}/share/renderer/print_studio.png" PROPERTIES QT_RESOURCE_ALIAS "print_studio.png")
  qt_add_resources(${target} gplatform_renderer_showcase_fixture PREFIX "/startup-tests/renderers" FILES
    "${_GPLATFORM_SDK_ROOT}/share/renderer/monkey.obj"
    "${_GPLATFORM_SDK_ROOT}/share/renderer/pillars_2k.hdr"
    "${_GPLATFORM_SDK_ROOT}/share/renderer/print_studio.png"
  )
endfunction()
set_property(GLOBAL PROPERTY GPLATFORM_RENDERER_BACKEND_TARGETS "RendererBackendVtk;RendererBackendFilament")
set(VTK_LIBRARIES "VTK::WrappingTools;VTK::ViewsQt;VTK::ViewsInfovis;VTK::CommonColor;VTK::ViewsContext2D;VTK::ViewsCore;VTK::loguru;VTK::TestingRendering;VTK::TestingCore;VTK::vtksys;VTK::RenderingQt;VTK::RenderingLabel;VTK::octree;VTK::RenderingLOD;VTK::RenderingLICOpenGL2;VTK::glad;VTK::RenderingImage;VTK::RenderingGridAxes;VTK::RenderingContextOpenGL2;VTK::RenderingCellGrid;VTK::fmt;VTK::nlohmannjson;VTK::RenderingVolumeOpenGL2;VTK::IOVeraOut;VTK::hdf5;VTK::IOTecplotTable;VTK::utf8;VTK::IOSegY;VTK::IOParallelXML;VTK::IOPLY;VTK::IOOggTheora;VTK::theora;VTK::ogg;VTK::IONetCDF;VTK::netcdf;VTK::IOMotionFX;VTK::pegtl;VTK::IOParallel;VTK::jsoncpp;VTK::IOMINC;VTK::IOLSDyna;VTK::IOLANLX3D;VTK::IOImport;VTK::IOIOSS;VTK::ioss;VTK::cgns;VTK::exodusII;VTK::zlib;VTK::IOHDF;VTK::IOFLUENTCFF;VTK::IOVideo;VTK::IOMovie;VTK::IOFDS;VTK::IOInfovis;VTK::libxml2;VTK::IOExportPDF;VTK::libharu;VTK::png;VTK::IOExportGL2PS;VTK::RenderingGL2PSOpenGL2;VTK::gl2ps;VTK::IOExodus;VTK::IOEngys;VTK::IOEnSight;VTK::IOERF;VTK::IOCityGML;VTK::pugixml;VTK::IOChemistry;VTK::IOCesium3DTiles;VTK::libproj;VTK::IOCONVERGECFD;VTK::IOHDFTools;VTK::IOCGNSReader;VTK::IOAsynchronous;VTK::IOExport;VTK::RenderingVtkJS;VTK::IOGeometry;VTK::RenderingSceneGraph;VTK::IOAMR;VTK::InteractionImage;VTK::InfovisLayout;VTK::ImagingStencil;VTK::ImagingStatistics;VTK::ImagingMorphological;VTK::ImagingMath;VTK::ImagingFourier;VTK::GUISupportQtSQL;VTK::IOSQL;VTK::sqlite;VTK::GUISupportQt;VTK::InteractionWidgets;VTK::RenderingVolume;VTK::RenderingAnnotation;VTK::InteractionStyle;VTK::ImagingHybrid;VTK::ImagingColor;VTK::GeovisCore;VTK::FiltersTopology;VTK::FiltersTensor;VTK::FiltersSelection;VTK::FiltersSMP;VTK::FiltersProgrammable;VTK::FiltersPoints;VTK::FiltersParallelImaging;VTK::FiltersTemporal;VTK::FiltersImaging;VTK::ImagingGeneral;VTK::FiltersGeometryPreview;VTK::FiltersGeneric;VTK::FiltersFlowPaths;VTK::eigen;VTK::FiltersAMR;VTK::FiltersParallel;VTK::FiltersTexture;VTK::FiltersModeling;VTK::DomainsChemistryOpenGL2;VTK::RenderingOpenGL2;VTK::RenderingHyperTreeGrid;VTK::RenderingUI;VTK::FiltersHybrid;VTK::DomainsChemistry;VTK::ChartsCore;VTK::InfovisCore;VTK::FiltersExtraction;VTK::ParallelDIY;VTK::diy2;VTK::IOXML;VTK::IOXMLParser;VTK::expat;VTK::ParallelCore;VTK::IOLegacy;VTK::IOCellGrid;VTK::FiltersCellGrid;VTK::token;VTK::IOCore;VTK::lz4;VTK::lzma;VTK::fast_float;VTK::FiltersStatistics;VTK::FiltersHyperTree;VTK::ImagingSources;VTK::IOImage;VTK::DICOMParser;VTK::jpeg;VTK::metaio;VTK::tiff;VTK::RenderingContext2D;VTK::RenderingFreeType;VTK::freetype;VTK::kwiml;VTK::RenderingCore;VTK::FiltersSources;VTK::ImagingCore;VTK::FiltersGeneral;VTK::FiltersVerdict;VTK::verdict;VTK::FiltersGeometry;VTK::CommonComputationalGeometry;VTK::FiltersCore;VTK::FiltersReduction;VTK::CommonExecutionModel;VTK::CommonDataModel;VTK::CommonSystem;VTK::CommonMisc;VTK::exprtk;VTK::CommonTransforms;VTK::CommonMath;VTK::kissfft;VTK::CommonCore;VTK::doubleconversion")
function(_gplatform_validate_framework)
  foreach(required BaseUI BaseTypes BaseGeometry BaseDB Document AppDB BaseInteraction BaseRender)
    if(NOT TARGET ${required})
      message(FATAL_ERROR "GPlatformSDK requires application framework target ${required}")
    endif()
  endforeach()
endfunction()
cmake_language(DEFER CALL _gplatform_validate_framework)
set(GPlatformSDK_FOUND TRUE)
